# Docker Compose per produzione
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=https://api.your-domain.com
    restart: unless-stopped
    networks:
      - havas-network

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl  # Certificati SSL
    depends_on:
      - frontend
    restart: unless-stopped
    networks:
      - havas-network

networks:
  havas-network:
    driver: bridge
